print("hello world")
print("i am a teacher")
print("weght:", 61)
print("county:", "mandera")
print("continent:", "africa")
print("graguated:", "False")
print('i love python')

print(type(61))
print(type(5.5))
print(type(False))
print("my name is"+"Ali"+"and i am"+"23"+"years old")
print("sum of x and y:", 45)

print("i wanna learn programming")
print("i am a teacher: " ,"true")
print("my height: ",5.7)
print("my mean score: ",75)
print("gender: ","male")

print(type(75))
print(type(5.7))
print(type(False))
print(type("male"))
print("my namme is "+"Ali"+" and i am "+"23"+ "years old")
print("sum of x and y is:",48)