name = input("enter your name: ")
print("my name is", name)
age = int(input("how old are you: "))
print("i am "+age+" years old")
school = input("enter your school: ")
print("my school is", school )
country = input("enter your country: ")
print("my country is", country)
num1 = int(input("enter first number:"))
num2 = int(input("enter second number: "))
sum = num1 + num2
print("sum:", sum)
name = input("enter your name: ")
age = int(input("enter your age: "))
name = input("what is your name? ")
age = int(input("hpw old are you? "))
country = input("enter your country: ")
print("my country is", country)
name = input("what is your name? ")
age = int(input("how old are you? "))
num1 = int(input("enter first no.: "))
num2 = int(input("enter second no.: "))
sum = num1 + num2
print("sum: ",sum)